/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGrafica;

import Core.Sistema;
import FuncoesDistribuicoes.Calculo;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author marco
 */
public class Simulacao extends javax.swing.JFrame {

    private Calculo calculoTEC;
    private Calculo calculoTS;
    private Sistema sistema;
    
    double ts;
    double tec;
    /**
     * Creates new form Teste1
     */
    public Simulacao() {
        initComponents();
        
    }
    
    public Simulacao(Calculo ts, Calculo tec, int tempoMaximo){
        initComponents();
        
        this.calculoTS = ts;
        this.calculoTEC = tec;
        
        sistema = new Sistema(tempoMaximo, calculoTS, calculoTEC);
        
        inicializar();
    }
    
    public void inicializar(){
            b_proximo.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    
                    if(isOver()){
                        atualizarTela();
                        telaFim();
                        return;
                    }
                    
                    sistema.executar();
                    atualizarTela();
                    
                }
            });
            
            b_proximaEnt.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    int i = sistema.getEntidadeEntraram();
                    
                    do{
                        if(isOver()){
                            atualizarTela();
                            telaFim();
                            return;
                        }
                        sistema.executar();
                    }while(i == sistema.getEntidadeEntraram());
                    
                        atualizarTela();
                }
            });
            
            b_fim.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    do{
                        if(isOver()){
                            atualizarTela();
                            telaFim();
                            return;
                        }
                        sistema.executar();
                    }while(sistema.getTempo() <= sistema.getTempoMaximo());
                    
                    atualizarTela();
                }
            });
        }

    public void atualizarTela(){
        tf_tempo.setText(String.valueOf(sistema.getTempo()));
        tf_tamFila.setText(sistema.getQtdFila().getLast().toString());
        tf_qtdEntDentro.setText(String.valueOf(sistema.getEntidadeEntraram()));
        tf_qtdEntFora.setText(String.valueOf(sistema.getEntidadeSairam()));
        tf_qtdMaxEntSis.setText(String.valueOf(sistema.getQtdMaximoEntidadeDentro()));
        tf_recLivre.setText(String.valueOf(sistema.rec.isRecursoLivre()));
        tf_tempoRestRec.setText(String.valueOf(sistema.rec.getContador()));
    }
    
    public boolean isOver(){
        return (sistema.getTempo() >= sistema.getTempoMaximo());
    }
    
    public void telaFim(){
        JOptionPane.showMessageDialog(rootPane, "Tempo limite alcançado, reinicie a simulação");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tf_tempo = new javax.swing.JTextField();
        tf_tamFila = new javax.swing.JTextField();
        tf_recLivre = new javax.swing.JTextField();
        tf_tempoRestRec = new javax.swing.JTextField();
        tf_qtdEntDentro = new javax.swing.JTextField();
        tf_qtdEntFora = new javax.swing.JTextField();
        tf_qtdMaxEntSis = new javax.swing.JTextField();
        b_proximo = new javax.swing.JButton();
        b_fim = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        b_proximaEnt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tf_tempo.setEditable(false);
        tf_tempo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tf_tempo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_tempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_tempoActionPerformed(evt);
            }
        });

        tf_tamFila.setEditable(false);
        tf_tamFila.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tf_tamFila.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tf_recLivre.setEditable(false);
        tf_recLivre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tf_recLivre.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tf_tempoRestRec.setEditable(false);
        tf_tempoRestRec.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tf_tempoRestRec.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tf_qtdEntDentro.setEditable(false);
        tf_qtdEntDentro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tf_qtdEntDentro.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tf_qtdEntFora.setEditable(false);
        tf_qtdEntFora.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tf_qtdEntFora.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tf_qtdMaxEntSis.setEditable(false);
        tf_qtdMaxEntSis.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tf_qtdMaxEntSis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        b_proximo.setText("Proximo tempo");

        b_fim.setText("Ultimo Tempo");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Tempo");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Qtd Entidades entraram");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Tamanho da Fila");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Recurso Livre?");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Tempo restante recurso");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Qtd Entidades sairam");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Qtd Max Entidades no Sistema");

        b_proximaEnt.setText("Proxima Entidade");
        b_proximaEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_proximaEntActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_proximaEnt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_proximo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_fim)
                .addGap(90, 90, 90))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tf_tempo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel1)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(tf_tamFila, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116)
                                .addComponent(tf_qtdMaxEntSis, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel7))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_qtdEntFora, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_qtdEntDentro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(tf_recLivre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_tempoRestRec, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_tempo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_tamFila, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_qtdMaxEntSis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_qtdEntDentro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_recLivre, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_qtdEntFora, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_tempoRestRec, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_proximo)
                    .addComponent(b_fim)
                    .addComponent(b_proximaEnt)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_tempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_tempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_tempoActionPerformed

    private void b_proximaEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_proximaEntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_proximaEntActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simulacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_fim;
    private javax.swing.JButton b_proximaEnt;
    private javax.swing.JButton b_proximo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tf_qtdEntDentro;
    private javax.swing.JTextField tf_qtdEntFora;
    private javax.swing.JTextField tf_qtdMaxEntSis;
    private javax.swing.JTextField tf_recLivre;
    private javax.swing.JTextField tf_tamFila;
    private javax.swing.JTextField tf_tempo;
    private javax.swing.JTextField tf_tempoRestRec;
    // End of variables declaration//GEN-END:variables
}
